const express = require("express");
const app = express();

app.use(express.json())


// http://localhost:3000/register
// Method: Post

// req => IncomingReq generated by nodeJS 
// res => outgoingRes generated bu nodeJS 
app.post("/register", (req, res) => {
    try{
        let data = req.body;
        clients.push(data);
        res.status(200).json({
            message: "Data stored successfully",
            data,
        });
    }catch(error){
        console.log(error);
    }
})

// http://localhost:3000/users
// Method: Get
app.get("/users", (req, res) => {
    try{
        res.json({
            statusCode: 200,
            message: "Data is sent successfully",
            data: clients
        })
    }catch(error){
        console.log(error);
    }
})

// http://localhost:3000/users/1
// Method: Get
app.get("/user/:id", (req, res) => {
    try{
        let userId = parseInt(req.params.id);
        let userData;
        for(let i = 0; i < clients.length; i++){
            if(clients[i].id == userId){
                userData = clients[i];
                break;
            }
        }
        res.json({
            statusCode: 200,
            message: "Data is sent successfully",
            data: userData
        })
    }catch(error){
        console.log(error);
        res.status(500).json({
            statusCode: 500,
            message: "Server error",
            message: error.message
        })
    }
})

// http://localhost:3000/users/1
// Method: PUT
app.put("/user/:id", (req, res) => {
    try{
        let userId = parseInt(req.params.id);
        let data = req.body;
        let user = clients.find((user) => {user.id = userId})
        if(data.userName) 
            user.userName = data.userName;
        if(data.password)
            user.password = data.password;
        res.status(200).json({
            message: "User updated successfully",
            data: user
        }) 
    }catch(error){
        console.log(error);
    }
})

// http://localhost:3000/users/1
// Method: Delete
app.delete("/user/:id", (req, res) => {
    try{
        let userId = parseInt(req.params.id);
        for(let i = 0; i < clients.length; i++){
            if(clients[i].id == userId){
                clients.splice(i, 1);
                return res.json({
                    statusCode: 200,
                    message: "User deleted successfully"
                })
            }
        }
        const err = new Error("User does not exist");
        err.statusCode = 400;
        throw err;
    }catch(error){
        res.status(error.statusCode).json({
            statusCode: error.statusCode,
            message: error.message
        })
    }
})

app.listen(3000, () => {
    console.log("Server running on port 3000");
})



























